const projects = [
    {
      title: "ACTUS",
      integrator: "MODO8",
      status: "production",
      state: "On-site CMES visit scheduled",
      shipDate: "Jul 1, 2026",
      contractValue: 253208.38,
      invoiced: 195000,
      nextInvoice: "$23,013 — SAT (10%)",
      lastInvoice: "$23,076 — Change Order",
      address: "Wautoma Plant Milk Specialties Global E. Chicago Road | Wautoma, WI 54982 | (612) 439-5212"
    },
    {
      title: "OCADO",
      integrator: "Temple Controls",
      status: "production",
      state: "Working On Phased Shipping and Installation",
      shipDate: "Jul 1, 2026",
      contractValue: 560517.34,
      invoiced: 218586.14,
      nextInvoice: "$109,293 — Initial Shipment",
      lastInvoice: "$109,293 — Engineering Complete",
      address: "9091 88th Ave, Pleasant Prairie, WI"
    },
    {
      title: "ADI / MALIN",
      integrator: "MALIN",
      status: "production",
      state: "Working On Phased Shipping",
      shipDate: "Jun 22, 2026",
      contractValue: 278500,
      invoiced: 194950,
      nextInvoice: "$55,700 — Initial Shipment",
      lastInvoice: "$83,550 — Engineering Complete",
      address: "3200 Richmond Rd, Easton, PA 18040"
    },
    {
      title: "ARHAUS",
      integrator: "Equipment Depot",
      status: "pulling",
      state: "Pulling job",
      shipDate: "Jul 2, 2026",
      contractValue: 48655,
      invoiced: 34058.50,
      nextInvoice: "$9,731 — Initial Shipment",
      lastInvoice: "$14,596.50 — Engineering Complete",
      address: "51 East Hines Hill Rd, Boston Heights, OH 44236 | James Coddington 216-276-3956"
    },
    {
      title: "FRONTIER DENTAL",
      integrator: "KPI",
      status: "purchasing",
      state: "Purchased — CHANGE ORDER?",
      shipDate: "Jul 21, 2026",
      contractValue: 350000,
      invoiced: 105000,
      nextInvoice: "$70,000 — Start of Manufacturing",
      lastInvoice: "$105,000 — PO Placement (30%)",
      address: "2500 W. Carey Ave, Bldg F, North Las Vegas, NV 89032"
    },
    {
      title: "CONVEYOR ON CASTERS",
      integrator: "Formic",
      status: "purchasing",
      state: "Paid in full — freight to be invoiced at ship",
      shipDate: "Aug 3, 2026",
      contractValue: 4938,
      invoiced: 4938,
      nextInvoice: "Freight — TBD at shipment",
      lastInvoice: "Paid in Full — PO 101087",
      address: "979 Corporate Blvd, Linthicum Heights, MD 21090"
    },
    {
      title: "PITNEY BOS",
      integrator: "Temple Controls",
      status: "engineering",
      state: "Working On CET Drawing",
      shipDate: "Jul 27, 2026",
      contractValue: 226822.25,
      invoiced: 90728.90,
      nextInvoice: "$68,046 — Engineering Complete (Jun 19)",
      lastInvoice: "$90,728 — Downpayment",
      address: "Pitney Bowes, 5071 W 74th St, Indianapolis, IN 46268"
    },
    {
      title: "LOLOI RUGS",
      integrator: "AI",
      status: "production",
      state: "Justin Needs to Program",
      shipDate: "Jul 27, 2026",
      contractValue: 187126,
      invoiced: 93563,
      nextInvoice: "$93,563 — Final Shipment (Net 15)",
      lastInvoice: "$93,563 — 50% Downpayment",
      address: "4550 Spring Valley Rd, Farmers Branch, TX 75244"
    },
    {
      title: "NEW HORIZONS",
      integrator: "Formic",
      status: "pre-procurement",
      state: "Pre-procurement — FAT terms",
      shipDate: "Jul 31, 2026",
      contractValue: 202665,
      invoiced: 60799.50,
      nextInvoice: "$60,799 — Design Acceptance (30%)",
      lastInvoice: "$60,799 — Order (30%) — PO 101076",
      address: "211 Woodlawn Avenue, Norwalk, OH 44857"
    },
    {
      title: "SPARTAN NASH",
      integrator: "Tompkins",
      status: "engineering",
      state: "Engineering — downpayment received",
      shipDate: "Aug 7, 2026",
      contractValue: 98637,
      invoiced: 49318.50,
      nextInvoice: "$29,591 — Engineering Complete (Jun 5, Net 15)",
      lastInvoice: "$49,318 — 50% Downpayment",
      address: "1300 West Elkhorn Avenue, Sioux Falls, SD 57101"
    },
    {
      title: "R2",
      integrator: "Automation Intelligence",
      status: "engineering",
      state: "Engineering — downpayment received",
      shipDate: "Aug 17, 2026",
      contractValue: 77310,
      invoiced: 38655,
      nextInvoice: "$23,193 — Ship Notification (30%, Net 30)",
      lastInvoice: "$38,655 — 50% Downpayment — MODO826014-R2",
      address: "Automation Intelligence LLC, 6181 Taylor Dr, Flint, MI 48507"
    },
    {
      title: "AMAZON CANADA",
      integrator: "SJF",
      status: "engineering",
      state: "Engineering — downpayment received",
      shipDate: "Aug 28, 2026",
      contractValue: 177856,
      invoiced: 71142.40,
      nextInvoice: "$53,356 — Engineering Complete (Jun 26, Net 30)",
      lastInvoice: "$71,142 — 40% Downpayment",
      address: "Ryder, 1530 Gamble Pl, Winnipeg, MB R3T 1N6, Canada"
    },
    {
      title: "FORSYTH",
      integrator: "CRG",
      status: "pre-procurement",
      state: "Pre-procurement — awaiting downpayment",
      shipDate: "Aug 10, 2026",
      contractValue: 41140,
      invoiced: 0,
      nextInvoice: "$20,570 — 50% Downpayment at PO",
      lastInvoice: "None yet",
      address: "Storage Solutions, 910 E. 169th Street, Westfield, IN 46074"
    },
  ];
